version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile
    ports:
      - "8000:8000"  # Map the container's port 8000 to the host's port 8000
    volumes:
      - .:/app  # Mount the current directory into the container's /app directory
    environment:
      - ENVIRONMENT=production  # Example environment variable
