version: '3.8'

networks:
  my_network:

volumes:
  mongo_data:

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
<<<<<<< HEAD
    volumes:
      - mongo_data:/data/db
=======
>>>>>>> 81972f329b84d8eaaa4297b654349c88519f1138
    networks:
      - my_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
<<<<<<< HEAD
      - my_networkcd
=======
      - my_network
>>>>>>> 81972f329b84d8eaaa4297b654349c88519f1138
