version: '3.8'

networks:
  my_network:

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /Users/nioushamaghsoudnia/data/db:/data/db
    networks:
      - my_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - my_network
