# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: media.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmedia.proto\x12\x05media\"/\n\x05Media\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\"\x1d\n\x0fGetMediaRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"/\n\x10GetMediaResponse\x12\x1b\n\x05media\x18\x01 \x01(\x0b\x32\x0c.media.Media\"1\n\x12\x43reateMediaRequest\x12\x1b\n\x05media\x18\x01 \x01(\x0b\x32\x0c.media.Media\"2\n\x13\x43reateMediaResponse\x12\x1b\n\x05media\x18\x01 \x01(\x0b\x32\x0c.media.Media2\x91\x01\n\x0cMediaService\x12;\n\x08GetMedia\x12\x16.media.GetMediaRequest\x1a\x17.media.GetMediaResponse\x12\x44\n\x0b\x43reateMedia\x12\x19.media.CreateMediaRequest\x1a\x1a.media.CreateMediaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'media_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIA']._serialized_start=22
  _globals['_MEDIA']._serialized_end=69
  _globals['_GETMEDIAREQUEST']._serialized_start=71
  _globals['_GETMEDIAREQUEST']._serialized_end=100
  _globals['_GETMEDIARESPONSE']._serialized_start=102
  _globals['_GETMEDIARESPONSE']._serialized_end=149
  _globals['_CREATEMEDIAREQUEST']._serialized_start=151
  _globals['_CREATEMEDIAREQUEST']._serialized_end=200
  _globals['_CREATEMEDIARESPONSE']._serialized_start=202
  _globals['_CREATEMEDIARESPONSE']._serialized_end=252
  _globals['_MEDIASERVICE']._serialized_start=255
  _globals['_MEDIASERVICE']._serialized_end=400
# @@protoc_insertion_point(module_scope)
