# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"+\n\x0fGetUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"-\n\x11\x43reateUserRequest\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\".\n\x12\x43reateUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2\x86\x01\n\x0bUserService\x12\x36\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12?\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERREQUEST']._serialized_start=20
  _globals['_GETUSERREQUEST']._serialized_end=48
  _globals['_GETUSERRESPONSE']._serialized_start=50
  _globals['_GETUSERRESPONSE']._serialized_end=93
  _globals['_CREATEUSERREQUEST']._serialized_start=95
  _globals['_CREATEUSERREQUEST']._serialized_end=140
  _globals['_CREATEUSERRESPONSE']._serialized_start=142
  _globals['_CREATEUSERRESPONSE']._serialized_end=188
  _globals['_USER']._serialized_start=190
  _globals['_USER']._serialized_end=237
  _globals['_USERSERVICE']._serialized_start=240
  _globals['_USERSERVICE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
